<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>TetherPars.Client</AssemblyName>
    <RootNamespace>TetherPars.Client</RootNamespace>
    <Version>0.1.0</Version>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
